DROP PROFILE USER;

CREATE PROFILE APP_USER LIMIT
    FAILED_LOGIN_ATTEMPTS   5
    PASSWORD_LOCK_TIME      7
    PASSWORD_LIFE_TIME      90
    SESSIONS_PER_USER       2
    CONNECT_TIME            1440
    IDLE_TIME               1440;

CONN sys/Badao2089 as SYSDBA
CREATE USER thangiss IDENTIFIED BY thangiss
TEMPORARY TABLESPACE TEMP
DEFAULT TABLESPACE USERS
QUOTA 100M ON users
PROFILE app_user;

GRANT CREATE SESSION TO thangiss;